feat: vscode extension
PreMiD/pmd pull request #87
Opened 2022-10-13 15:58 UTC by Slowlife01

2022-10-17 08:34 UTC, Slowlife01 commented
Might add translate command later

2022-10-17 13:34 UTC, Slowlife01 commented
![image](https://user-images.githubusercontent.com/54318514/196190283-1f92d22e-5d63-4afb-8602-af4c30602cf9.png)
Would be nice if someone could fix this, if I exclude these files the modules below won't work
![image](https://user-images.githubusercontent.com/54318514/196190633-1277ae77-d68f-4855-b872-5b5d9ddb60b1.png)

2022-10-19 08:27 UTC, Slowlife01 commented
Should be fine now, please test it

2022-10-24 08:09 UTC, Bas950 reviewed
Maybe move apps/extensions and apps/cli to the main folder?

2022-10-24 08:19 UTC, Bas950 requested changes

2022-10-24 08:19 UTC, Bas950 commented on cli/LICENSE
> +../../LICENSE
this ../ probs aint correct anymore

2022-10-24 08:22 UTC, Bas950 reviewed
something to discuss with @Timeraa, should we .gitignore the bin folder or not.

2022-11-11 11:18 UTC, Timeraa commented
Sorry for the delay, why aren't you reusing classes like the ModuleManager from the cli or things like fetchSchema? I noticed that you are reusing other functions from it but not everything.

2022-12-06 20:26 UTC, Bas950 commented
![image](https://user-images.githubusercontent.com/34792838/206015447-a7fba852-cc74-4e00-a4e2-ebc1741c2d09.png)
Its impossible to see what you are inputting after you have touched the input field, a URL for image, thumbnail, website url? what url?

2022-12-07 20:16 UTC, Bas950 commented
![image](https://user-images.githubusercontent.com/34792838/206286391-1236f5ff-85e1-4fa0-bf6a-3d2141051f56.png)
is it me or does enter not do anything now?

2022-12-08 01:54 UTC, Slowlife01 commented
> ![image](https://user-images.githubusercontent.com/34792838/206286391-1236f5ff-85e1-4fa0-bf6a-3d2141051f56.png)
> is it me or does enter not do anything now?

I think the validation failed and it doesn't show the error message

2022-12-09 18:08 UTC, Bas950 commented
![image](https://user-images.githubusercontent.com/34792838/206765636-8fe47963-2438-4dbc-a695-a57441c249a1.png)

2023-02-05 15:22 UTC, Timeraa commented
Hey @Slowlife01,

Sorry this took so long to get reviewed, lot's of things came into my way.

Can you resolve the conflicts on this PR? I also have some improvements you could add to the Extension which you can add now or after the initial release:

- When modifying a Presence, you could automatically open the Presence's files (presence.ts &/ metadata.json) or show a popup like you already do when you created the Presence 
![image](https://user-images.githubusercontent.com/29104008/216828090-d118652a-7518-4c4b-8149-0526e300f644.png)
- When you freshly cloned the repository, you could automatically install the dependencies when you run modify/create a Presence
- When you are already modifying a Presence and run the command again it should stop the old running compiler as it's no longer needed (imo don't be afraid to give your thoughts on it)
- Perhaps you can add Open metadata.json to this popup as well
![image](https://user-images.githubusercontent.com/29104008/216828119-7c7aa05b-24fd-41cb-8893-44b461a2101e.png)

I have also found some errors in the Extension:
- If you run the compiler (modify) and then kill the terminal of it
![image](https://user-images.githubusercontent.com/29104008/216827951-48678fa5-d1ba-4d7e-ba32-a7798c0c1180.png)
You get this error: 
![image](https://user-images.githubusercontent.com/29104008/216827973-f9e57d6d-4ff7-4eee-b4d0-72f3310b8b92.png)


Also once I opened the package.json DeepScan showed me this, maybe take a look at that? 
![image](https://user-images.githubusercontent.com/29104008/216828172-e0926c60-0d02-4a72-89b7-6b29f65b1d14.png)

2023-02-05 16:04 UTC, Timeraa requested changes

2023-02-05 16:04 UTC, Timeraa commented on README.md
> +
Just an empty line add?

2023-02-05 16:04 UTC, Timeraa commented on cli/LICENSE
> +../LICENSE
I am not sure but can you do it like that?

2023-02-05 16:04 UTC, Timeraa commented on cli/tsconfig.json
> +  "exclude": ["templete"]
typo `templete` > `template`

2023-02-05 16:04 UTC, Timeraa commented on cli/tsconfig.json
> +  "include": ["./src/**/*"],
Pretty sure this can be removed as `rootDir` is src

2023-02-05 16:04 UTC, Timeraa commented on extension/.vscode/launch.json
> +}
File not needed since you have it in root

2023-02-05 16:04 UTC, Timeraa commented on extension/.vscode/tasks.json
> +
ditto

2023-02-05 16:04 UTC, Timeraa commented on extension/LICENSE
> +../LICENSE
Does it work like that?

2023-02-05 16:04 UTC, Timeraa commented on extension/.vscodeignore
> +yarn.lock
shouldn't this be ´pnpm-lock.yaml` instead of `yarn.lock`?

2023-02-05 16:04 UTC, Timeraa commented on extension/package.json
> +  "name": "vspmd",
I think this should be `PreMiD pmd` as it's project bound to not cause any conflicts?

2023-02-06 13:22 UTC, Slowlife01 commented
>When you are already modifying a Presence and run the command again it should stop the old running compiler as it's no longer needed (imo don't be afraid to give your thoughts on it)

Bas wanted it to be able to compile multiple Presences at the same time

2023-02-06 15:42 UTC, Slowlife01 commented on README.md
> +
*Will remove it for now since I'm not really good at writing one*

2023-02-24 17:25 UTC, Timeraa approved these changes

2023-02-25 18:35 UTC, Bas950 approved these changes

2023-02-25 18:41 UTC, merged